using WowPacketParser.Misc;

namespace WowPacketParser.Enums.Version.V0_9_1_3810
{
    public static class Opcodes_0_9_1
    {
        public static BiDictionary<Opcode, int> Opcodes(Direction direction)
        {
            switch (direction)
            {
                case Direction.ClientToServer:
                case Direction.BNClientToServer:
                    return ClientOpcodes;
                case Direction.ServerToClient:
                case Direction.BNServerToClient:
                    return ServerOpcodes;
                default:
                    return MiscOpcodes;
            }
        }

        private static readonly BiDictionary<Opcode, int> ClientOpcodes = new BiDictionary<Opcode, int>
        {
            {Opcode.CMSG_ACCEPT_TRADE, 280},
            {Opcode.CMSG_ACTIVATE_TAXI, 427},
            {Opcode.CMSG_AREA_TRIGGER, 180},
            {Opcode.CMSG_ATTACK_STOP, 320},
            {Opcode.CMSG_ATTACK_SWING, 319},
            {Opcode.CMSG_AUTH_SESSION, 491},
            {Opcode.CMSG_AUTO_EQUIP_ITEM, 264},
            {Opcode.CMSG_AUTOSTORE_LOOT_ITEM, 262},
            {Opcode.CMSG_BEGIN_TRADE, 277},
            {Opcode.CMSG_BUY_ITEM, 416},
            {Opcode.CMSG_CANCEL_CAST, 301},
            {Opcode.CMSG_CANCEL_CHANNELLING, 313},
            {Opcode.CMSG_CANCEL_TRADE, 282},
            {Opcode.CMSG_CAST_SPELL, 300},
            {Opcode.CMSG_CHAR_DELETE, 56},
            {Opcode.CMSG_ENUM_CHARACTERS, 55},
            {Opcode.CMSG_QUERY_CREATURE, 96},
            {Opcode.CMSG_DUEL_ACCEPTED, 362},
            {Opcode.CMSG_FORCE_MOVE_ROOT_ACK, 231},
            {Opcode.CMSG_FORCE_MOVE_UNROOT_ACK, 233},
            {Opcode.CMSG_QUERY_GAME_OBJECT, 94},
            {Opcode.CMSG_GAME_OBJ_USE, 177},
            {Opcode.CMSG_GM_TICKET_GET_TICKET, 527},
            {Opcode.CMSG_GOSSIP_HELLO, 377},
            {Opcode.CMSG_GOSSIP_SELECT_OPTION, 378},
            {Opcode.CMSG_QUERY_GUILD_INFO, 84},
            {Opcode.CMSG_INITIATE_TRADE, 276},
            {Opcode.CMSG_INSPECT, 274},
            {Opcode.CMSG_ITEM_QUERY_SINGLE, 86},
            {Opcode.CMSG_CHAT_JOIN_CHANNEL, 151},
            {Opcode.CMSG_CHAT_LEAVE_CHANNEL, 152},
            {Opcode.CMSG_LIST_INVENTORY, 412},
            {Opcode.CMSG_LOGOUT_REQUEST, 75},
            {Opcode.CMSG_LOOT_UNIT, 347},
            {Opcode.CMSG_LOOT_RELEASE, 349},
            {Opcode.CMSG_MESSAGECHAT, 149},
            {Opcode.CMSG_NAME_QUERY, 80},
            {Opcode.CMSG_NEW_SPELL_SLOT, 299},
            {Opcode.CMSG_QUERY_NPC_TEXT, 381},
            {Opcode.CMSG_PET_ACTION, 371},
            {Opcode.CMSG_QUERY_PET_NAME, 82},
            {Opcode.CMSG_PET_SET_ACTION, 370},
            {Opcode.CMSG_PING, 474},
            {Opcode.CMSG_PLAYER_LOGIN, 61},
            {Opcode.CMSG_PLAYER_LOGOUT, 74},
            {Opcode.CMSG_QUERY_TIME, 460},
            {Opcode.CMSG_QUEST_GIVER_CHOOSE_REWARD, 396},
            {Opcode.CMSG_QUEST_GIVER_COMPLETE_QUEST, 392},
            {Opcode.CMSG_QUEST_GIVER_HELLO, 386},
            {Opcode.CMSG_QUEST_GIVER_STATUS_QUERY, 384},
            {Opcode.CMSG_QUERY_QUEST_INFO, 92},
            {Opcode.CMSG_REQUEST_PET_INFO, 631},
            {Opcode.CMSG_GHOST, 485},
            {Opcode.CMSG_SET_ACTION_BUTTON, 294},
            {Opcode.CMSG_SET_ACTIVE_MOVER, 616},
            {Opcode.CMSG_SET_SELECTION, 315},
            {Opcode.CMSG_SET_TARGET_OBSOLETE, 316},
            {Opcode.CMSG_SET_TRADE_GOLD, 285},
            {Opcode.CMSG_SET_TRADE_ITEM, 283},
            {Opcode.CMSG_SWAP_INV_ITEM, 267},
            {Opcode.CMSG_SWAP_ITEM, 266},
            {Opcode.CMSG_TAXI_NODE_STATUS_QUERY, 424},
            {Opcode.CMSG_TAXI_QUERY_AVAILABLE_NODES, 426},
            {Opcode.CMSG_UPDATE_ACCOUNT_DATA, 521},
            {Opcode.CMSG_USE_ITEM, 171},
            {Opcode.CMSG_ZONEUPDATE, 498}
        };

        private static readonly BiDictionary<Opcode, int> ServerOpcodes = new BiDictionary<Opcode, int>
        {
            {Opcode.SMSG_ACCOUNT_DATA_TIMES, 519},
            {Opcode.SMSG_UPDATE_ACTION_BUTTONS, 295},
            {Opcode.SMSG_ACTIVATE_TAXI_REPLY, 428},
            {Opcode.SMSG_AI_REACTION, 314},
            {Opcode.SMSG_ATTACKER_STATE_UPDATE, 328},
            {Opcode.SMSG_ATTACK_START, 321},
            {Opcode.SMSG_ATTACK_STOP, 322},
            {Opcode.SMSG_AUTH_CHALLENGE, 490},
            {Opcode.SMSG_AUTH_RESPONSE, 492},
            {Opcode.SMSG_BIND_POINT_UPDATE, 339},
            {Opcode.SMSG_CAST_FAILED, 302},
            {Opcode.SMSG_CHANNEL_NOTIFY, 153},
            {Opcode.SMSG_DELETE_CHAR, 60},
            {Opcode.SMSG_ENUM_CHARACTERS_RESULT, 59},
            {Opcode.SMSG_COMPRESSED_UPDATE_OBJECT, 500},
            {Opcode.SMSG_COOLDOWN_EVENT, 307},
            {Opcode.SMSG_CORPSE_RECLAIM_DELAY, 615},
            {Opcode.SMSG_QUERY_CREATURE_RESPONSE, 97},
            {Opcode.SMSG_DESTROY_OBJECT, 170},
            {Opcode.SMSG_DUEL_COMPLETE, 360},
            {Opcode.SMSG_DUEL_REQUESTED, 357},
            {Opcode.SMSG_DUEL_WINNER, 361},
            {Opcode.SMSG_EMOTE, 257},
            {Opcode.SMSG_ENCHANTMENT_LOG, 469},
            {Opcode.SMSG_ENVIRONMENTAL_DAMAGE_LOG, 506},
            {Opcode.SMSG_EXPLORATION_EXPERIENCE, 502},
            {Opcode.SMSG_FISH_ESCAPED, 455},
            {Opcode.SMSG_FISH_NOT_HOOKED, 454},
            {Opcode.SMSG_FORCE_MOVE_ROOT, 230},
            {Opcode.SMSG_FORCE_MOVE_UNROOT, 232},
            {Opcode.SMSG_FRIEND_LIST, 103},
            {Opcode.SMSG_GAME_OBJECT_CUSTOM_ANIM, 179},
            {Opcode.SMSG_GAME_OBJECT_DESPAWN, 531},
            {Opcode.SMSG_QUERY_GAME_OBJECT_RESPONSE, 95},
            {Opcode.SMSG_GAMEOBJECT_SPAWN_ANIM, 530},
            {Opcode.SMSG_GAME_TIME_UPDATE, 67},
            {Opcode.SMSG_GM_TICKET_GET_TICKET, 528},
            {Opcode.SMSG_GOSSIP_COMPLETE, 380},
            {Opcode.SMSG_GOSSIP_MESSAGE, 379},
            {Opcode.SMSG_GROUP_LIST, 125},
            {Opcode.SMSG_QUERY_GUILD_INFO_RESPONSE, 85},
            {Opcode.SMSG_IGNORE_LIST, 107},
            {Opcode.SMSG_INITIALIZE_FACTIONS, 288},
            {Opcode.SMSG_SEND_KNOWN_SPELLS, 296},
            {Opcode.SMSG_INSPECT_RESULT, 275},
            {Opcode.SMSG_INVENTORY_CHANGE_FAILURE, 272},
            {Opcode.SMSG_ITEM_ENCHANT_TIME_UPDATE, 489},
            {Opcode.SMSG_ITEM_PUSH_RESULT, 356},
            {Opcode.SMSG_ITEM_QUERY_SINGLE_RESPONSE, 88},
            {Opcode.SMSG_VENDOR_INVENTORY, 413},
            {Opcode.SMSG_LOGIN_SET_TIME_SPEED, 66},
            {Opcode.SMSG_LOGOUT_COMPLETE, 77},
            {Opcode.SMSG_LOGOUT_RESPONSE, 76},
            {Opcode.SMSG_LOG_XP_GAIN, 462},
            {Opcode.SMSG_LOOT_RELEASE, 351},
            {Opcode.SMSG_LOOT_REMOVED, 352},
            {Opcode.SMSG_LOOT_RESPONSE, 350},
            {Opcode.SMSG_CHAT, 150},
            {Opcode.SMSG_ON_MONSTER_MOVE, 221},
            {Opcode.SMSG_MOVE_SET_NORMAL_FALL, 241},
            {Opcode.SMSG_QUERY_PLAYER_NAME_RESPONSE, 81},
            {Opcode.SMSG_NEW_WORLD, 62},
            {Opcode.SMSG_PRINT_NOTIFICATION, 457},
            {Opcode.SMSG_QUERY_NPC_TEXT_RESPONSE, 382},
            {Opcode.SMSG_PARTY_MEMBER_PARTIAL_STATE, 126},
            {Opcode.SMSG_SPELL_PERIODIC_AURA_LOG, 588},
            {Opcode.SMSG_PET_CAST_FAILED, 310},
            {Opcode.SMSG_QUERY_PET_NAME_RESPONSE, 83},
            {Opcode.SMSG_PET_SPELLS_MESSAGE, 375},
            {Opcode.SMSG_PLAYER_BOUND, 342},
            {Opcode.SMSG_PONG, 475},
            {Opcode.SMSG_QUERY_TIME_RESPONSE, 461},
            {Opcode.SMSG_QUEST_GIVER_OFFER_REWARD_MESSAGE, 395},
            {Opcode.SMSG_QUEST_GIVER_QUEST_COMPLETE, 399},
            {Opcode.SMSG_QUEST_GIVER_QUEST_LIST_MESSAGE, 387},
            {Opcode.SMSG_QUEST_GIVER_STATUS, 385},
            {Opcode.SMSG_QUEST_UPDATE_ADD_ITEM, 408},
            {Opcode.SMSG_QUERY_QUEST_INFO_RESPONSE, 93},
            {Opcode.SMSG_RESISTLOG, 468},
            {Opcode.SMSG_SET_PROFICIENCY, 293},
            {Opcode.SMSG_SET_REST_START, 540},
            {Opcode.SMSG_SHOW_TAXI_NODES, 423},
            {Opcode.SMSG_SPELL_DAMAGE_SHIELD, 589},
            {Opcode.SMSG_SPELL_DISPELL_LOG, 633},
            {Opcode.SMSG_SPELL_EXECUTE_LOG, 586},
            {Opcode.SMSG_SPELL_MISS_LOG, 585},
            {Opcode.SMSG_SPELL_NON_MELEE_DAMAGE_LOG, 590},
            {Opcode.SMSG_SPELL_DELAYED, 480},
            {Opcode.SMSG_SPELL_FAILURE, 305},
            {Opcode.SMSG_SPELL_GO, 304},
            {Opcode.SMSG_SPELL_START, 303},
            {Opcode.SMSG_TAXI_NODE_STATUS, 425},
            {Opcode.SMSG_TEXT_EMOTE, 259},
            {Opcode.SMSG_TRADE_STATUS, 286},
            {Opcode.SMSG_TRADE_STATUS_EXTENDED, 287},
            {Opcode.SMSG_TRAINER_BUY_SUCCEEDED, 433},
            {Opcode.SMSG_TRANSFER_PENDING, 63},
            {Opcode.SMSG_TUTORIAL_FLAGS, 251},
            {Opcode.SMSG_UPDATE_AURA_DURATION, 309},
            {Opcode.SMSG_UPDATE_OBJECT, 169},
            {Opcode.SMSG_ZONE_UNDER_ATTACK, 594}
        };

        private static readonly BiDictionary<Opcode, int> MiscOpcodes = new BiDictionary<Opcode, int>
        {
            {Opcode.MSG_CHANNEL_START, 311},
            {Opcode.MSG_CHANNEL_UPDATE, 312},
            {Opcode.MSG_LOOKING_FOR_GROUP, 509},
            {Opcode.MSG_MOVE_FALL_LAND, 201},
            {Opcode.MSG_MOVE_HEARTBEAT, 236},
            {Opcode.MSG_MOVE_JUMP, 187},
            {Opcode.MSG_MOVE_ROOT, 234},
            {Opcode.MSG_MOVE_SET_FACING, 218},
            {Opcode.MSG_MOVE_SET_PITCH, 219},
            {Opcode.MSG_MOVE_SET_RUN_MODE, 194},
            {Opcode.MSG_MOVE_SET_RUN_SPEED, 205},
            {Opcode.MSG_MOVE_SET_SWIM_SPEED, 211},
            {Opcode.MSG_MOVE_START_BACKWARD, 182},
            {Opcode.MSG_MOVE_START_FORWARD, 181},
            {Opcode.MSG_MOVE_START_STRAFE_LEFT, 184},
            {Opcode.MSG_MOVE_START_STRAFE_RIGHT, 185},
            {Opcode.MSG_MOVE_START_SWIM, 202},
            {Opcode.MSG_MOVE_START_TURN_LEFT, 188},
            {Opcode.MSG_MOVE_START_TURN_RIGHT, 189},
            {Opcode.MSG_MOVE_STOP, 183},
            {Opcode.MSG_MOVE_STOP_STRAFE, 186},
            {Opcode.MSG_MOVE_STOP_SWIM, 203},
            {Opcode.MSG_MOVE_STOP_TURN, 190},
            {Opcode.MSG_MOVE_TELEPORT, 197},
            {Opcode.MSG_MOVE_TELEPORT_ACK, 199},
            {Opcode.MSG_MOVE_UNROOT, 235},
            {Opcode.MSG_MOVE_WORLDPORT_ACK, 220}
        };
    }
}
