using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_0_45166
{
    public class AreaTriggerData : IAreaTriggerData
    {
        public WowGuid Caster { get; set; }
        public uint Duration { get; set; }
        public uint TimeToTarget { get; set; }
        public uint TimeToTargetScale { get; set; }
        public uint TimeToTargetExtraScale { get; set; }
        public int SpellID { get; set; }
        public int SpellForVisuals { get; set; }
        public int SpellXSpellVisualID { get; set; }
        public float BoundsRadius2D { get; set; }
        public uint DecalPropertiesID { get; set; }
        public WowGuid CreatingEffectGUID { get; set; }
        public WowGuid Field_80  { get; set; }
        public IScaleCurve OverrideScaleCurve { get; set; }
        public IScaleCurve ExtraScaleCurve { get; set; }
        public IVisualAnim VisualAnim { get; set; }
    }
}

