using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_0_45166
{
    public class DynamicObjectData : IDynamicObjectData
    {
        public WowGuid Caster { get; set; }
        public byte Type { get; set; }
        public int SpellXSpellVisualID  { get; set; }
        public int SpellID { get; set; }
        public float Radius { get; set; }
        public uint CastTime { get; set; }
    }
}

