using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_0_45166
{
    public class ObjectData : IObjectData
    {
        public int EntryID { get; set; }
        public uint TypeID { get; set; }
        public uint DynamicFlags { get; set; }
        public float Scale { get; set; }

        public IObjectData Clone() { return (IObjectData)MemberwiseClone(); }
    }
}

