using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_0_45166
{
    public class PVPInfo : IPVPInfo
    {
        public uint WeeklyPlayed { get; set; }
        public uint WeeklyWon { get; set; }
        public uint SeasonPlayed { get; set; }
        public uint SeasonWon { get; set; }
        public uint Rating { get; set; }
        public uint WeeklyBestRating { get; set; }
        public uint SeasonBestRating { get; set; }
        public uint PvpTierID { get; set; }
        public uint WeeklyBestWinPvpTierID { get; set; }
        public uint Field_28 { get; set; }
        public uint Field_2C { get; set; }
        public bool Disqualified { get; set; }
    }
}

