using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_1_47014
{
    public class ArenaCooldown : IArenaCooldown
    {
        public int SpellID { get; set; }
        public int Charges { get; set; }
        public int Unk254 { get; set; }
        public uint Flags { get; set; }
        public uint StartTime { get; set; }
        public uint EndTime { get; set; }
        public uint NextChargeTime { get; set; }
        public byte MaxCharges { get; set; }
    }
}

