using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_1_47014
{
    public class RestInfo : IRestInfo
    {
        public uint Threshold { get; set; }
        public byte StateID { get; set; }
    }
}

