using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_1_47014
{
    public class SkillInfo : ISkillInfo
    {
        public ushort[] SkillLineID { get; } = new ushort[256];
        public ushort[] SkillStep { get; } = new ushort[256];
        public ushort[] SkillRank { get; } = new ushort[256];
        public ushort[] SkillStartingRank { get; } = new ushort[256];
        public ushort[] SkillMaxRank { get; } = new ushort[256];
        public short[] SkillTempBonus { get; } = new short[256];
        public ushort[] SkillPermBonus { get; } = new ushort[256];
    }
}

