using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_1_47014
{
    public class VisualAnim : IVisualAnim
    {
        public uint AnimationDataID { get; set; }
        public uint AnimKitID { get; set; }
        public uint AnimProgress { get; set; }
        public bool IsDecay { get; set; }
    }
}

